name: Instanciate music

on: 
    #workflow_dispatch
    schedule:
    #- cron:  '0 */6 * * *'
    - cron: '30 3,9,15,21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SECRET_SSH_TO_CONFIGFILES_PRIVATE_KEY }}
        repository: jackett2/configfiles
        path: ./CONFIGFILES_PRIVATE

    - name: What time is it ?
      run: |
        date -u
        TZ="Europe/Paris" date
    
    - name: Install some packages
      run: |
        set -xe
        APT='sudo apt -y -qq -o=Dpkg::Use-Pty=0'
        $APT update
        $APT install axel bmon colordiff fd-find ffmpeg htop nmon nmap ncat socat parallel python3 python3-dev python3-pip python3-virtualenv rar ripgrep virtualenvwrapper unrar
        
    - name: Populate $CONFIGFILES_PRIVATE env var
      run: echo "CONFIGFILES_PRIVATE=$GITHUB_WORKSPACE/CONFIGFILES_PRIVATE" >> $GITHUB_ENV

    - name: Tweak some config and start the services
      continue-on-error: true
      run: |
        set -xe
        
        
    - name: Start tunnel
      run: |
        timeout 350m ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -R ${{ secrets.SECRET_SSH_RUNNER_PORT }}:localhost:22 ${{ secrets.SECRET_SSH_RUNNER_GW }}
