name: Instanciate public services

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup serveo keys
      run: |
        set -xe
                
        #mkdir -p ~/.ssh
        #chmod 600 ~/.ssh/id_rsa
        #ssh -T -o StrictHostKeyChecking=no -R ${{ secrets.SECRET_SERVEO_IV_FQDN }}:80:localhost:3000 serveo.net

    - name: Setup Cloudflared
      run: |
        set -xe

        cd /tmp/
        wget -nv https://github.com/cloudflare/cloudflared/releases/download/2024.5.0/cloudflared-linux-amd64 -O cfd
        chmod u+x cfd
  
    - name: Run Invidious
      run: |
        set -xe
        
        cd /tmp/
        git clone https://github.com/iv-org/invidious.git
        cd invidious
        sed -i 's/CHANGE_ME!!/${{ secrets.SECRET_INV_HMAC_KEY }}/g' docker-compose.yml
        docker compose up -d

    - name: Run tunnels
      run: |
        set -xe
        
        cd /tmp/
        #nohup ./certstream-server > nohup.out 2> nohup.err < /dev/null & 
        
        nohup ./cfd tunnel --url http://localhost:3000 --logfile /tmp/lol > nohup.out 2> nohup.err < /dev/null &
        sleep 5
        newurl=$(grep -Poa "https://(.*)trycloudflare.com" /tmp/lol)        
