name: Instanciate public services

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Test
      run: |
        set -xe

        mkdir -p ~/.ssh
        echo "${{ secrets.SECRET_SSH_KEY_PRIVATE }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -R iv.serveo.net:80:localhost:3000 serveo.net
        
        cd /tmp/
        
        git clone https://github.com/iv-org/invidious.git
        cd invidious
        sed -i 's/CHANGE_ME!!/${{ secrets.SECRET_INV_HMAC_KEY }}/g' docker-compose.yml
        docker compose up -d

        #ssh -o StrictHostKeyChecking=no -R inv.serveo.net:80:localhost:3000 serveo.net
