name: Instanciate public GH SSH

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SECRET_SSH_TO_CONFIGFILES_PRIVATE_KEY }}
        repository: jackett2/configfiles
        path: ./CONFIGFILES_PRIVATE

    - name: Populate $CONFIGFILES_PRIVATE envvar
      run: echo "CONFIGFILES_PRIVATE=$GITHUB_WORKSPACE/CONFIGFILES_PRIVATE" >> $GITHUB_ENV

    - name: SSH tweak
      run: |
        set -xe
        sudo cp -f $CONFIGFILES_PRIVATE/sshd/sshd_config /etc/ssh/sshd_config

        echo "runner:password" > pass
        sudo chpasswd < pass

    - name: SSH
      run: |
        set -xe
        sudo cat /etc/passwd
        sudo cat /etc/shadow
        
        sudo cat /etc/ssh/sshd_config

        sudo service ssh start

    - name: Run tunnel
      run: |
        set -xe
        ssh -T -o StrictHostKeyChecking=no -R 1025:localhost:22 serveo.net
