name: Instanciate public GH SSH

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SECRET_SSH_TO_CONFIGFILES_PRIVATE_KEY }}
        repository: jackett2/configfiles
        path: ./CONFIGFILES_PRIVATE

    - name: Populate $CONFIGFILES_PRIVATE env var
      run: echo "CONFIGFILES_PRIVATE=$GITHUB_WORKSPACE/CONFIGFILES_PRIVATE" >> $GITHUB_ENV

    - name: SSH tweak and start the service
      run: |
        set -xe
        sudo cp -f $CONFIGFILES_PRIVATE/sshd/sshd_config /etc/ssh/sshd_config
        sudo cp -f $CONFIGFILES_PRIVATE/sshd/bashrc ~/.bashrc
        sudo cp -f $CONFIGFILES_PRIVATE/sshd/bash_profile ~/.bash_profile

        echo "runner:${{ secrets.SECRET_SSH_RUNNER_PASSWORD }}" > pass
        sudo chpasswd < pass

        #sudo cat /etc/passwd
        #sudo cat /etc/shadow
        #sudo cat /etc/ssh/sshd_config
        
        sudo service ssh start
        
    - name: Start tunnel
      run: |
        set -xe
        ssh -o StrictHostKeyChecking=no -R ${{ secrets.SECRET_SSH_RUNNER_PORT }}:localhost:22 serveo.net
