name: Instanciate public GH SSH

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SECRET_SSH_TO_CONFIGFILES_PRIVATE_KEY }}
        repository: jackett2/configfiles
        path: ./CONFIGFILES_PRIVATE

    - name: Install some packages
      run: |
        set -xe
        sudo apt -y -qq -o=Dpkg::Use-Pty=0 update
        sudo apt -y -qq -o=Dpkg::Use-Pty=0 install bmon colordiff fd-find htop nmon nmap ncat socat parallel python3 python3-dev python3-pip python3-virtualenv virtualenvwrapper 
        
    - name: Populate $CONFIGFILES_PRIVATE env var
      run: echo "CONFIGFILES_PRIVATE=$GITHUB_WORKSPACE/CONFIGFILES_PRIVATE" >> $GITHUB_ENV

    - name: Tweak some config and start the SSH service
      run: |
        set -xe
        sudo cp -f $CONFIGFILES_PRIVATE/sshd/sshd_config /etc/ssh/sshd_config
        sudo cp -f $CONFIGFILES_PRIVATE/sshd/bashrc ~/.bashrc
        sudo cp -f $CONFIGFILES_PRIVATE/sshd/bash_profile ~/.bash_profile

        echo "runner:${{ secrets.SECRET_SSH_RUNNER_PASSWORD }}" > pass
        sudo chpasswd < pass

        sudo rm -rf /etc/update-motd.d/10-help-text
        sudo rm -rf /etc/update-motd.d/9*
        sudo rm -rf /etc/legal

        #sudo cat /etc/passwd
        #sudo cat /etc/shadow
        #sudo cat /etc/ssh/sshd_config
        
        sudo service ssh start
        
    - name: Start tunnel
      run: |
        set -xe
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -R ${{ secrets.SECRET_SSH_RUNNER_PORT }}:localhost:22 serveo.net
